### PR TITLE
Azure assignment - Enh/1/azure flask

### PR DESCRIPTION
**Pull request by JayashreeS11**
The following are completed:

1. A storage account (jayashrees11storage) is created in Azure, inside which a container (jayashrees11container) is present with  folders - folder1, folder2, folder3
2. A flask app (app.py) is created for printing the contents of the folder. The flask app renders to a html file (file_list.html) which displays the list of files.
3. A Virtual Machine (jayashrees11vm) is created in Azure inside a Vnet (jayashrees11vnet) and Subnet
4. The inbound traffic is streamlined for tcp at port 5000, and the source ip is Tiger VPN.
5. The flask app is deployed and run inside the VM
6. The app displays the files present inside the folder (which is given as a query parameter in the URL)

With VPN : 
Screenshot 2024-05-14 170053
Without VPN:
Screenshot 2024-05-14 161240
Cost:
Screenshot 2024-05-14 172959

### CODE REVIEW

**Comment by sarangunasekara** [comment]
Looks good, can you pls add all the screenshots in the README.md file.

**Comment by JayashreeS11** [comment]
> Looks good, can you pls add all the screenshots in the README.md file.

I have done that now Saran

**Comment by sarangunasekara** [comment]
@JayashreeS11 as soon as u rename all the screenshot files, I will merge ur PR.

**Comment by JayashreeS11** [comment]
> @JayashreeS11 as soon as u rename all the screenshot files, I will merge ur PR.

I have renamed them Saran

**Review by sarangunasekara — COMMENTED** [review]
This looks good, pls be noted that whenever you add any files, have a proper filename for them, and have a descriptive readme.

**Pull request merged**
